# Korean anatomical terms for the circulatory diagram.
# "a. and v." is the drawing's shorthand for an artery/vein pair.
TERMS = {
    "A. = artery": "a. = 동맥",
    "V. = vein": "v. = 정맥",
    "Heart": "심장",
    "Aorta": "대동맥",
    "Descending aorta": "내림대동맥",
    "Superior vena cava": "위대정맥",
    "Inferior vena cava": "아래대정맥",
    "Pulmonary a. and v.": "허파동맥·정맥",
    "Coronary a. and v.": "심장동맥·정맥",
    # 머리·목
    "Common carotid a.": "온목동맥",
    "Internal carotid a.": "속목동맥",
    "External carotid a.": "바깥목동맥",
    "Internal jugular v.": "속목정맥",
    "External jugular v.": "바깥목정맥",
    "Vertebral a.": "척추동맥",
    "Basilar a.": "뇌바닥동맥",
    "Venous sinuses": "정맥굴",
    # 팔
    "Subclavian a. and v.": "빗장밑동맥·정맥",
    "Axillary a. and v.": "겨드랑동맥·정맥",
    "Brachial a. and v.": "위팔동맥·정맥",
    "Cephalic v.": "노쪽피부정맥",
    "Basilic v.": "자쪽피부정맥",
    "Median cubital v.": "팔오금중간정맥",
    "Radial a.": "노동맥",
    "Ulnar a.": "자동맥",
    "Palmar digital v.": "손바닥쪽손가락정맥",
    "Digital a.": "손가락동맥",
    # 배
    "Celiac trunk": "복강동맥",
    "Superior mesenteric a. and v.": "위창자간막동맥·정맥",
    "Renal a. and v.": "콩팥동맥·정맥",
    "Gonadal a. and v.": "생식샘동맥·정맥",
    "Hepatic v.": "간정맥",
    "(Hepatic) portal v.": "간문맥",
    "Splenic a. and v.": "지라동맥·정맥",
    # 다리
    "Common iliac a. and v.": "온엉덩동맥·정맥",
    "Internal iliac a. and v.": "속엉덩동맥·정맥",
    "External iliac a. and v.": "바깥엉덩동맥·정맥",
    "Common femoral a. and v.": "온넙다리동맥·정맥",
    "Femoral a. and v.": "넙다리동맥·정맥",
    "Deep femoral a. and v.": "깊은넙다리동맥·정맥",
    "Great saphenous v.": "큰두렁정맥",
    "Small saphenous v.": "작은두렁정맥",
    "Popliteal a. and v.": "오금동맥·정맥",
    "Anterior tibial a. and v.": "앞정강동맥·정맥",
    "Posterior tibial a. and v.": "뒤정강동맥·정맥",
    "Peroneal a. and v.": "종아리동맥·정맥",
    "Arcuate a.": "활동맥",
    "Dorsal digital a.": "발등쪽발가락동맥",
    "Dorsal digital vein": "발등쪽발가락정맥",
    "Dorsal venous arch": "발등정맥활",
    # Editor's note in the source file — not part of the illustration.
    "To modify: read User:Jmarchn/Edition of Inkscape draw with layers": "",
}
