"""Visible label -> id for the circulatory diagram.

The two legend lines are deliberately absent: they explain the drawing's
shorthand rather than naming a vessel, so there is nothing to click.
"""

IDS = {
    "간문맥": "portal-vein",
    "간정맥": "hepatic-vein",
    "겨드랑동맥·정맥": "axillary",
    "깊은넙다리동맥·정맥": "deep-femoral",
    "내림대동맥": "descending-aorta",
    "넙다리동맥·정맥": "femoral",
    "노동맥": "radial",
    "노쪽피부정맥": "cephalic",
    "뇌바닥동맥": "basilar",
    "대동맥": "aorta",
    "뒤정강동맥·정맥": "posterior-tibial",
    "바깥목동맥": "external-carotid",
    "바깥목정맥": "external-jugular",
    "바깥엉덩동맥·정맥": "external-iliac",
    "발등정맥활": "dorsal-venous-arch",
    "발등쪽발가락동맥": "dorsal-digital-artery",
    "발등쪽발가락정맥": "dorsal-digital-vein",
    "복강동맥": "celiac",
    "빗장밑동맥·정맥": "subclavian",
    "생식샘동맥·정맥": "gonadal",
    "속목동맥": "internal-carotid",
    "속목정맥": "internal-jugular",
    "속엉덩동맥·정맥": "internal-iliac",
    "손가락동맥": "digital-artery",
    "손바닥쪽손가락정맥": "palmar-digital-vein",
    "심장": "heart",
    "심장동맥·정맥": "coronary",
    "아래대정맥": "ivc",
    "앞정강동맥·정맥": "anterior-tibial",
    "오금동맥·정맥": "popliteal",
    "온넙다리동맥·정맥": "common-femoral",
    "온목동맥": "common-carotid",
    "온엉덩동맥·정맥": "common-iliac",
    "위대정맥": "svc",
    "위창자간막동맥·정맥": "superior-mesenteric",
    "위팔동맥·정맥": "brachial",
    "자동맥": "ulnar",
    "자쪽피부정맥": "basilic",
    "작은두렁정맥": "small-saphenous",
    "정맥굴": "venous-sinus",
    "종아리동맥·정맥": "fibular",
    "지라동맥·정맥": "splenic",
    "척추동맥": "vertebral",
    "콩팥동맥·정맥": "renal",
    "큰두렁정맥": "great-saphenous",
    "팔오금중간정맥": "median-cubital",
    "허파동맥·정맥": "pulmonary",
    "활동맥": "arcuate",
}
