"""Visible label -> id for the respiratory diagram.

Run after relabel.py, which unwraps the multilingual <switch> wrappers, joins
the seven two-line labels and puts the Korean in. Keying by the visible word is
safe at that point: the four that read the same in English — Superior lobe,
Inferior lobe, Oblique fissure and their partners — become 오른위엽 and 왼위엽,
오른빗틈새 and 왼빗틈새, and all forty-eight names are distinct.
"""

IDS = {
    "코": "nose",
    "코안": "nasal-cavity",
    "코선반": "nasal-conchae",
    "코안뜰": "nasal-vestibule",
    "코곁굴": "paranasal-sinuses",
    "이마굴": "frontal-sinus",
    "나비굴": "sphenoid-sinus",
    "인두": "pharynx",
    "후두": "larynx",
    "후두덮개": "epiglottis",
    "방패연골": "thyroid-cartilage",
    "반지연골": "cricoid-cartilage",
    "성대주름": "vocal-folds",
    "입안": "oral-cavity",
    "식도": "esophagus",
    "기관": "trachea",
    "기관갈림": "carina",
    "주기관지": "main-bronchi",
    "엽기관지": "lobar-bronchus",
    "혀구역 기관지": "lingular-bronchi",
    "기관·기관지 연골고리": "cartilage-rings",
    "위엽 기관지": "superior-bronchus",
    "중간엽 기관지": "middle-bronchus",
    "아래엽 기관지": "inferior-bronchus",
    "오른허파": "right-lung",
    "왼허파": "left-lung",
    "오른위엽": "right-superior-lobe",
    "왼위엽": "left-superior-lobe",
    "오른중간엽": "right-middle-lobe",
    "오른아래엽": "right-inferior-lobe",
    "왼아래엽": "left-inferior-lobe",
    "수평틈새": "horizontal-fissure",
    "오른빗틈새": "right-oblique-fissure",
    "왼빗틈새": "left-oblique-fissure",
    "심장패임": "cardiac-notch",
    "허파혀": "lingula",
    "왼허파꼭대기": "left-apex",
    "가로막": "diaphragm",
    "모세혈관그물": "capillary-beds",
    "결합조직": "connective-tissue",
    "허파꽈리주머니": "alveolar-sacs",
    "허파꽈리관": "alveolar-duct",
    "점액샘": "mucous-gland",
    "점막": "mucosal-lining",
    "허파동맥": "pulmonary-artery",
    "허파정맥": "pulmonary-vein",
    "허파꽈리": "alveoli",
    "허파꽈리방": "alveolar-atrium",
}
